name: CI security of ginkgo

on: [push]ginkgo-oneAPI

jobs:
  build:qsub -I -l nodes=1:gpu:ppn=2 -d .

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |make all && make run qsub -I -l nodes=1:gpu:ppn=2 -d .
        echo Add other actions to build,
        echo test, and deploy your project.
